### ISSUE TITLE
卧槽原来你也是看视频这些学的

### ISSUE THREAD

**Issue by Yin-FR** [Novmbrain/MyLearningNote#1]
我之前以为计算机专业的学校都会教这些框架啥的

**Comment by Yin-FR** [comment]
感觉你这个也太全了，是个很好的软开学习路线 😄

**Comment by Novmbrain** [comment]
感觉这些工作中用的东西，就算CS专业的也不教

**Comment by Novmbrain** [comment]
> 感觉你这个也太全了，是个很好的软开学习路线 😄

 杂七杂八看了一堆orz，里面有些笔记对应的课确实不错

**Comment by Yin-FR** [comment]
> > 感觉你这个也太全了，是个很好的软开学习路线 😄
> 
> 杂七杂八看了一堆orz，里面有些笔记对应的课确实不错

你这笔记是自己记的吗 😱

**Comment by Novmbrain** [comment]
> > > 感觉你这个也太全了，是个很好的软开学习路线 😄
> > 
> > 
> > 杂七杂八看了一堆orz，里面有些笔记对应的课确实不错
> 
> 你这笔记是自己记的吗 😱

嗯嗯，都是之前写的学习笔记，主要是一二年级写的。Cesure 期间啥都没学 LoL
